# This Containerfile expects a secret named "creds" to contain
# the registry pull secret.  To build, use e.g. 
# podman build --secret id=creds,src=$HOME/.config/containers/auth.json --secret id=gateway-admin-password,src=$HOME/secrets/gateway-admin-password ...
FROM registry.redhat.io/rhel9/rhel-bootc:latest

USER root

COPY containers-auth.conf /usr/lib/tmpfiles.d/link-podman-credentials.conf
RUN --mount=type=secret,id=creds,required=true cp /run/secrets/creds /usr/lib/container-auth.json && \
    chmod 0600 /usr/lib/container-auth.json && \
    ln -sr /usr/lib/container-auth.json /etc/ostree/auth.json

# Install base packages
RUN dnf \
    --enablerepo=rhel-9-for-x86_64-baseos-rpms \
    --enablerepo=rhel-9-for-x86_64-appstream-rpms \
    install -y \
    podman \
    tmux \
    mkpasswd \
    && dnf clean all \
    && rm -rf /var/{cache,log} /var/lib/{dnf,rhsm}

RUN mkdir -p /etc/ignition/data \ 
    && chmod 777 /etc/ignition/data

COPY etc/containers/systemd/ignition.container /etc/containers/systemd/ignition.container

RUN /usr/libexec/podman/quadlet --dryrun

EXPOSE 8088
EXPOSE 8043

CMD [ "/sbin/init" ]
