# This Containerfile expects a secret named "creds" to contain
# the registry pull secret.  To build, use e.g. 
# podman build --secret id=creds,src=$HOME/.config/containers/auth.json ...
FROM registry.redhat.io/rhel9/rhel-bootc:latest

USER root

ARG OPA_VERSION=v1.3.0

COPY containers-auth.conf /usr/lib/tmpfiles.d/link-podman-credentials.conf
RUN --mount=type=secret,id=creds,required=true cp /run/secrets/creds /usr/lib/container-auth.json && \
    chmod 0600 /usr/lib/container-auth.json && \
    ln -sr /usr/lib/container-auth.json /etc/ostree/auth.json

# Install base packages
RUN dnf \
    --enablerepo=rhel-9-for-x86_64-baseos-rpms \
    --enablerepo=rhel-9-for-x86_64-appstream-rpms \
    install -y \
    podman \
    tmux \
    mkpasswd \
    && dnf clean all \
    && rm -rf /var/{cache,log} /var/lib/{dnf,rhsm}

RUN pass=$(mkpasswd --method=SHA-512 --rounds=4096 redhat) && \
    groupadd ops && \
    groupadd developers && \
    useradd -m -G wheel admin -p $pass && \
    useradd -m -G ops devops1 -p $pass && \
    useradd -m -G developers dev1 -p $pass  

RUN echo "%wheel        ALL=(ALL)       NOPASSWD: ALL" > /etc/sudoers.d/freewheelers

RUN mkdir -p /etc/opa/policies

# Copy default policies
COPY etc/opa/policies /etc/opa/policies

# Copy the quadlet file
# COPY etc/containers/systemd/opa-server.container /etc/containers/systemd/opa-server.container

# Download and install OPA as systemd service
RUN curl -L -o /usr/local/bin/opa https://github.com/open-policy-agent/opa/releases/download/$OPA_VERSION/opa_linux_amd64 && \
    chmod 755 /usr/local/bin/opa

COPY etc/systemd/system/opa.service /etc/systemd/system/opa.service

RUN systemctl enable opa.service 

# RUN /usr/libexec/podman/quadlet --dryrun
    
# Copy the pam opa validation script
COPY scripts/ /usr/local/bin/

RUN chmod +x /usr/local/bin/pam_opa_validation.sh && \
    chmod +x /usr/local/bin/update_pam_config.sh

RUN /usr/local/bin/update_pam_config.sh

CMD [ "/sbin/init" ]
    