# This Containerfile expects a secret named "creds" to contain
# the registry pull secret.  To build, use e.g. 
# podman build --secret id=creds,src=$HOME/.config/containers/auth.json ...
FROM registry.redhat.io/rhel9/rhel-bootc:latest

COPY containers-auth.conf /usr/lib/tmpfiles.d/link-podman-credentials.conf
RUN --mount=type=secret,id=creds,required=true cp /run/secrets/creds /usr/lib/container-auth.json && \
    chmod 0600 /usr/lib/container-auth.json && \
    ln -sr /usr/lib/container-auth.json /etc/ostree/auth.json

# Install base system packages and utilities
RUN dnf \
    --enablerepo=rhel-9-for-x86_64-baseos-rpms \
    --enablerepo=rhel-9-for-x86_64-appstream-rpms \
    install -y \
    podman \
    vim-enhanced \
    NetworkManager-wifi \
    git \
    buildah \
    skopeo \
    lorax \
    ansible-core \
    && dnf clean all \
    && rm -rf /var/{cache,log} /var/lib/{dnf,rhsm}

# Install workstation package group
RUN dnf \
--enablerepo=rhel-9-for-x86_64-baseos-rpms \
--enablerepo=rhel-9-for-x86_64-appstream-rpms \
groupinstall -y \
workstation \
--excludepkgs=rootfiles \
&& dnf clean all \
&& rm -rf /var/{cache,log} /var/lib/{dnf,rhsm}

# Install EPEL
RUN dnf \
    --enablerepo=codeready-builder-for-rhel-9-x86_64-rpms \
    install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm \
    && dnf clean all \
    && rm -rf /var/{cache,log} /var/lib/{dnf,rhsm}

# Install OCP cli and packages to make install media
RUN dnf \
    --enablerepo=rhocp-4.18-for-rhel-9-x86_64-rpms \
    install -y \
    openshift-clients \
    nmstate \
    && dnf clean all \
    && rm -rf /var/{cache,log} /var/lib/{dnf,rhsm}

    
# Install rdesktop from EPEL
RUN dnf \
    install -y \
    rdesktop \
    htop \
    && dnf clean all \
    && rm -rf /var/{cache,log} /var/lib/{dnf,rhsm}

RUN dnf \
    remove -y epel-release-latest-9 \
    && dnf clean all \
    && rm -rf /var/{cache,log} /var/lib/{dnf,rhsm}

RUN systemctl set-default graphical.target

# Resize windows on super+mouse-right-click
RUN gsettings set org.gnome.desktop.wm.preferences resize-with-right-button "true"

# Install all RPMs in ./additional_rpms
RUN --mount=type=bind,source=./additional_rpms,target=/additional_rpms,Z \
	dnf -y --disablerepo='*' install --skip-unavailable /additional_rpms/*.rpm \
	; dnf -y clean all

CMD [ "/sbin/init" ]